<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <RootNamespace>Arrow.Http.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Arrow.Http.Client.Tests" />
    <InternalsVisibleTo Include="Arrow.Http.Client.Net48.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arrow.Data\Arrow.Data.csproj" />
    <ProjectReference Include="..\Arrow.Jobs.Abstractions\Arrow.Jobs.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <PackageReference Include="PolySharp" Version="1.14.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Net.Http.Json" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="System.Threading.Channels" Version="9.0.0" />
  </ItemGroup>

</Project>
