<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arrow.Http.AspNetCore\Arrow.Http.AspNetCore.csproj" />
    <ProjectReference Include="..\Arrow.Jobs.AspNetCore\Arrow.Jobs.AspNetCore.csproj" />
  </ItemGroup>

</Project>
