<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Arrow.Jobs.Redis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arrow.Jobs.Abstractions\Arrow.Jobs.Abstractions.csproj" />
    <ProjectReference Include="..\Arrow.Jobs.InMemory\Arrow.Jobs.InMemory.csproj" />
  </ItemGroup>

</Project>
