import { emptyModulePath } from "@/lib/workspace-paths";

export interface WorkspaceMenuItem {
  id: string;
  title: string;
  titleTr: string;
  url: string;
  category: "Katalog" | "İşlemler" | "Raporlar" | "Ayarlar" | "Seri & Parti" | "Araçlar";
  workspace: string;
  description: string;
  keywords: string[];
}

export interface WorkspaceSearchConfig {
  workspace: string;
  name: string;
  nameTr: string;
  examples: string[];
}

export const WORKSPACE_SEARCH_CONFIGS: Record<string, WorkspaceSearchConfig> = {
  all: {
    workspace: "all",
    name: "System",
    nameTr: "Tüm Modüller",
    examples: ["stok bakiye", "bilanço", "work order", "fason"],
  },
  system: {
    workspace: "system",
    name: "System",
    nameTr: "Tüm Modüller",
    examples: ["stok bakiye", "bilanço", "work order", "fason"],
  },
  stock: {
    workspace: "stock",
    name: "Stock",
    nameTr: "Stok",
    examples: ["depo bakiyeleri", "mal kabul", "ürün ağacı"],
  },
  accounting: {
    workspace: "accounting",
    name: "Accounting",
    nameTr: "Muhasebe & Finans",
    examples: ["general ledger", "balance sheet", "mizan"],
  },
  manufacturing: {
    workspace: "manufacturing",
    name: "Manufacturing",
    nameTr: "Üretim",
    examples: ["bom", "work order", "üretim planı"],
  },
  subcontracting: {
    workspace: "subcontracting",
    name: "Subcontracting",
    nameTr: "Fason & Tedarik",
    examples: ["inward order", "fason teslimat", "purchase order"],
  },
  selling: {
    workspace: "selling",
    name: "Selling",
    nameTr: "Satış",
    // Satış araması kapsamı hem selling modüllerini hem fason (cross kural)
    // öğelerini içerir; örnekler iki kapsamı da temsil eder.
    examples: ["sipariş", "teklif", "fason teslimat"],
  },
};

const e = emptyModulePath;

export const STOCK_WORKSPACE_MENU_ITEMS: WorkspaceMenuItem[] = [
  // Katalog
  {
    id: "stock_item",
    title: "Item",
    titleTr: "Stok Kartı / Malzeme",
    url: "/stock/item",
    category: "Katalog",
    workspace: "stock",
    description: "Stok kalemleri, ürün kartları, malzeme ve ürün katalog yönetimi.",
    keywords: ["ürün", "malzeme", "stok kartı", "item", "ürünler", "stok listesi"],
  },
  {
    id: "stock_item_group",
    title: "Item Group",
    titleTr: "Ürün Grubu",
    url: e("stock", "Item Group"),
    category: "Katalog",
    workspace: "stock",
    description: "Stok kalemlerinin kategorize edildiği ürün grupları.",
    keywords: ["ürün grubu", "kategori", "stok grubu", "item group"],
  },
  {
    id: "stock_product_bundle",
    title: "Product Bundle",
    titleTr: "Ürün Ağacı / Set (Bundle)",
    url: e("stock", "Product Bundle"),
    category: "Katalog",
    workspace: "stock",
    description: "Birden fazla stok kaleminden oluşan paket ürünler ve ürün ağacı paketleri.",
    keywords: ["ürün ağacı", "bundle", "paket", "set", "ürün paketi"],
  },
  {
    id: "stock_item_price",
    title: "Item Price",
    titleTr: "Ürün Fiyat Listesi",
    url: e("stock", "Item Price"),
    category: "Katalog",
    workspace: "stock",
    description: "Satış ve satın alma ürün fiyat tanımları.",
    keywords: ["fiyat", "ürün fiyatı", "fiyat listesi", "item price"],
  },
  {
    id: "stock_shipping_rule",
    title: "Shipping Rule",
    titleTr: "Kargo & Sevkiyat Kuralı",
    url: e("stock", "Shipping Rule"),
    category: "Katalog",
    workspace: "stock",
    description: "Sevkiyat ve nakliye ücret hesaplama kuralları.",
    keywords: ["kargo", "sevkiyat", "nakliye", "shipping"],
  },
  {
    id: "stock_pricing_rule",
    title: "Pricing Rule",
    titleTr: "Fiyatlandırma & İndirim Kuralı",
    url: e("stock", "Pricing Rule"),
    category: "Katalog",
    workspace: "stock",
    description: "Otomatik indirimler, kampanya ve özel fiyatlandırma kuralları.",
    keywords: ["indirim", "kampanya", "fiyat kuralı", "pricing rule"],
  },
  {
    id: "stock_item_alternative",
    title: "Item Alternative",
    titleTr: "Muadil / İkame Ürün",
    url: e("stock", "Item Alternative"),
    category: "Katalog",
    workspace: "stock",
    description: "Bir stok kaleminin yerine kullanılabilecek muadil ve alternatif malzemeler.",
    keywords: ["muadil", "alternatif", "ikame", "eşdeğer"],
  },
  {
    id: "stock_item_manufacturer",
    title: "Item Manufacturer",
    titleTr: "Ürün Üreticisi",
    url: e("stock", "Item Manufacturer"),
    category: "Katalog",
    workspace: "stock",
    description: "Stok kalemlerinin üretici ve tedarikçi marka eşleşmeleri.",
    keywords: ["üretici", "manufacturer", "tedarikçi marka"],
  },

  // İşlemler
  {
    id: "stock_material_request",
    title: "Material Request",
    titleTr: "Malzeme Talebi",
    url: e("stock", "Material Request"),
    category: "İşlemler",
    workspace: "stock",
    description: "Depolar arası transfer veya satın alma için malzeme talep belgesi.",
    keywords: ["talep", "malzeme talebi", "satın alma talebi", "transfer talebi"],
  },
  {
    id: "stock_entry",
    title: "Stock Entry",
    titleTr: "Stok Giriş / Çıkış / Transfer Fişi",
    url: e("stock", "Stock Entry"),
    category: "İşlemler",
    workspace: "stock",
    description: "Depolar arası stok transferi, üretime malzeme çıkışı, zayiat ve stok giriş fişleri.",
    keywords: ["stok fişi", "stok girişi", "stok çıkışı", "transfer fişi", "zayiat"],
  },
  {
    id: "stock_delivery_note",
    title: "Delivery Note",
    titleTr: "Teslimat İrsaliyesi",
    url: e("stock", "Delivery Note"),
    category: "İşlemler",
    workspace: "stock",
    description: "Müşteriye gönderilen ürünlerin çıkışını sağlayan sevk irsaliyesi.",
    keywords: ["irsaliye", "teslimat", "sevk irsaliyesi", "delivery note"],
  },
  {
    id: "stock_purchase_receipt",
    title: "Purchase Receipt",
    titleTr: "Satın Alma Mal Kabul İrsaliyesi",
    url: e("stock", "Purchase Receipt"),
    category: "İşlemler",
    workspace: "stock",
    description: "Tedarikçiden gelen malzemelerin depoya kabul irsaliyesi.",
    keywords: ["mal kabul", "satın alma irsaliyesi", "giriş irsaliyesi", "purchase receipt"],
  },
  {
    id: "stock_pick_list",
    title: "Pick List",
    titleTr: "Toplama Listesi (Pick List)",
    url: e("stock", "Pick List"),
    category: "İşlemler",
    workspace: "stock",
    description: "Depodan siparişlerin hazırlanması için malzeme toplama emri.",
    keywords: ["toplama listesi", "pick list", "depo toplama", "sipariş toplama"],
  },
  {
    id: "stock_delivery_trip",
    title: "Delivery Trip",
    titleTr: "Sevkiyat Rotalaması",
    url: e("stock", "Delivery Trip"),
    category: "İşlemler",
    workspace: "stock",
    description: "Araç sevkiyat rotaları ve teslimat tur planlaması.",
    keywords: ["sevkiyat rotası", "teslimat rotası", "araç rotası", "delivery trip"],
  },

  // Raporlar
  {
    id: "stock_ledger",
    title: "Stock Ledger",
    titleTr: "Stok Hareket / Defteri Raporu",
    url: "/stock/stock-ledger",
    category: "Raporlar",
    workspace: "stock",
    description: "Stok giriş, çıkış ve devir hareketlerinin detaylı kronolojik kaydı.",
    keywords: ["stok hareketi", "ekstre", "stok defteri", "ledger", "giriş çıkış"],
  },
  {
    id: "stock_balance",
    title: "Stock Balance",
    titleTr: "Stok Bakiye Raporu",
    url: "/stock/stock-balance",
    category: "Raporlar",
    workspace: "stock",
    description: "Depo bazında anlık stok miktarları, serbest stok ve bakiye değerleri.",
    keywords: ["stok bakiyesi", "bakiye", "depo stokları", "kullanılabilir stok", "stok durumu"],
  },
  {
    id: "stock_analytics",
    title: "Stock Analytics",
    titleTr: "Stok Analitik & Trend Raporu",
    url: "/stock/stock-analytics",
    category: "Raporlar",
    workspace: "stock",
    description: "Aylık/yıllık stok giriş-çıkış trendleri, grafikler ve stok devir analizi.",
    keywords: ["analiz", "stok analizi", "trend", "grafik", "stok devir hızı"],
  },
  {
    id: "stock_retail_sales_report",
    title: "Retail Sales Report",
    titleTr: "Perakende Satış Raporu",
    url: "/stock/retail-sales-report",
    category: "Raporlar",
    workspace: "stock",
    description: "Perakende satışların tarih, mağaza, ürün ve tutar bazlı analizini yapar. Günlük, haftalık veya aylık satış trendlerini gösterir.",
    keywords: ["perakende satış", "satış raporu", "mağaza satış", "retail sales"],
  },
  {
    id: "stock_projected_qty",
    title: "Stock Projected Qty",
    titleTr: "Gelecek / Tahmini Stok Miktarı",
    url: e("stock", "Stock Projected Qty"),
    category: "Raporlar",
    workspace: "stock",
    description: "Gelecek siparişler ve talepler dahil beklenen projeksiyon stok miktarları.",
    keywords: ["projeksiyon", "tahmini stok", "beklenen stok", "projected qty"],
  },
  {
    id: "stock_summary",
    title: "Stock Summary",
    titleTr: "Stok Özet Raporu",
    url: e("stock", "Stock Summary"),
    category: "Raporlar",
    workspace: "stock",
    description: "Ürün grubu ve depo bazında genel stok özeti.",
    keywords: ["stok özeti", "genel bakiye özeti", "özet"],
  },
  {
    id: "stock_ageing",
    title: "Stock Ageing",
    titleTr: "Stok Yaşlandırma Raporu",
    url: e("stock", "Stock Ageing"),
    category: "Raporlar",
    workspace: "stock",
    description: "Depoda bekleme süresine göre ölü ve yavaş hareket gören stok yaşlandırması.",
    keywords: ["yaşlandırma", "ölü stok", "bekleyen ürünler", "ageing"],
  },
  {
    id: "stock_warehouse_wise_balance",
    title: "Warehouse Wise Stock Balance",
    titleTr: "Depo Bazlı Stok Bakiye Raporu",
    url: e("stock", "Warehouse Wise Stock Balance"),
    category: "Raporlar",
    workspace: "stock",
    description: "Her bir depo için ayrı ayrı stok miktarları ve bakiye dağılımı.",
    keywords: ["depo bazlı stok", "depo bakiyeleri", "lokasyon stokları"],
  },

  // Seri & Parti
  {
    id: "stock_serial_no",
    title: "Serial No",
    titleTr: "Seri Numaraları",
    url: e("stock", "Serial No"),
    category: "Seri & Parti",
    workspace: "stock",
    description: "Tekil ürün seri numaralarının takibi ve kayıtları.",
    keywords: ["seri numarası", "serial no", "seri no takibi", "cihaz seri no"],
  },
  {
    id: "stock_batch",
    title: "Batch",
    titleTr: "Parti / Lot Numaraları",
    url: e("stock", "Batch"),
    category: "Seri & Parti",
    workspace: "stock",
    description: "Üretim ve son kullanma tarihli parti/lot takibi.",
    keywords: ["parti", "lot", "batch", "parti no", "son kullanma tarihi"],
  },
  {
    id: "stock_serial_batch_traceability",
    title: "Serial No and Batch Traceability",
    titleTr: "Seri No ve Parti İzlenebilirlik Raporu",
    url: "/stock/serial-batch-traceability",
    category: "Seri & Parti",
    workspace: "stock",
    description: "Hangi seri no veya lot hangi müşteriye satıldı veya hangi tedarikçiden geldi izlenebilirliği.",
    keywords: ["izlenebilirlik", "seri no takibi", "lot takibi", "traceability"],
  },

  // Ayarlar
  {
    id: "stock_settings",
    title: "Stock Settings",
    titleTr: "Stok Genel Ayarları",
    url: e("stock", "Stock Settings"),
    category: "Ayarlar",
    workspace: "stock",
    description: "Stok modülü varsayılan ayarları, değerleme yöntemi (FIFO/Ağırlıklı Ortalama) ve izinler.",
    keywords: ["stok ayarları", "fifo", "maliyet yöntemi", "değerleme"],
  },
  {
    id: "stock_warehouse",
    title: "Warehouse",
    titleTr: "Depolar / Lokasyonlar",
    url: e("stock", "Warehouse"),
    category: "Ayarlar",
    workspace: "stock",
    description: "Depo ağacı, fiziksel ve mantıksal depo lokasyon tanımları.",
    keywords: ["depo", "warehouse", "lokasyon", "antrepo", "şube deposu"],
  },
  {
    id: "stock_uom",
    title: "Unit of Measure",
    titleTr: "Ölçü Birimleri (UOM)",
    url: e("stock", "Unit of Measure"),
    category: "Ayarlar",
    workspace: "stock",
    description: "Adet, kg, metre, koli gibi stok ölçü birimleri tanımları.",
    keywords: ["birim", "ölçü birimi", "uom", "adet", "kg"],
  },
  {
    id: "stock_brand",
    title: "Brand",
    titleTr: "Marka Tanımları",
    url: e("stock", "Brand"),
    category: "Ayarlar",
    workspace: "stock",
    description: "Stok kalemlerine atanabilecek marka kataloğu.",
    keywords: ["marka", "brand", "ürün markası"],
  },

  // Araçlar
  {
    id: "stock_reconciliation",
    title: "Stock Reconciliation",
    titleTr: "Stok Sayım & Düzeltme Fişi",
    url: e("stock", "Stock Reconciliation"),
    category: "Araçlar",
    workspace: "stock",
    description: "Fiziksel sayım sonrası sistem stok miktarlarını güncelleme ve sayım farkı düzeltme.",
    keywords: ["sayım", "stok sayımı", "stok düzeltme", "reconciliation", "sayım farkı"],
  },
  {
    id: "stock_quick_balance",
    title: "Quick Stock Balance",
    titleTr: "Hızlı Stok Sayım Bakiyesi",
    url: e("stock", "Quick Stock Balance"),
    category: "Araçlar",
    workspace: "stock",
    description: "Anlık hızlı stok miktarı sorgulama ve kontrol ekranı.",
    keywords: ["hızlı sayım", "anlık bakiye", "hızlı bakiye"],
  },
  {
    id: "stock_landed_cost_voucher",
    title: "Landed Cost Voucher",
    titleTr: "İthalat / Nakliye Maliyeti Dağıtımı",
    url: "/landed-cost-voucher",
    category: "Araçlar",
    workspace: "stock",
    description: "Gümrük, kargo ve ek maliyetlerin ürün stok maliyetine yansıtılması.",
    keywords: ["maliyet dağıtımı", "ithalat maliyeti", "landed cost", "gümrük"],
  },
  {
    id: "stk_reports_group",
    title: "Reports",
    titleTr: "Raporlar",
    url: e("stock", "Reports"),
    category: "Raporlar",
    workspace: "stock",
    description: "Stok raporları toplu modülü.",
    keywords: ["stok raporları", "stock reports", "stok analizi", "trend"],
  },
  {
    id: "stk_purchase_receipt_trends",
    title: "Purchase Receipt Trends",
    titleTr: "Mal Kabul Trendleri",
    url: e("stock", "Purchase Receipt Trends"),
    category: "Raporlar",
    workspace: "stock",
    description: "Mal kabul hareketlerinin trend analizi.",
    keywords: ["mal kabul trend", "purchase receipt", "giriş trendi", "mal kabul"],
  },
  {
    id: "stk_delivery_note_trends",
    title: "Delivery Note Trends",
    titleTr: "Teslimat Notu Trendleri",
    url: e("stock", "Delivery Note Trends"),
    category: "Raporlar",
    workspace: "stock",
    description: "Teslimat/irsaliye hareketlerinin trend analizi.",
    keywords: ["teslimat trend", "delivery note", "çıkış trendi", "sevk"],
  },
];

export const ACCOUNTING_WORKSPACE_MENU_ITEMS: WorkspaceMenuItem[] = [
  {
    id: "acc_general_ledger",
    title: "General Ledger",
    titleTr: "Genel Defter / Muhasebe Ekstresi",
    url: e("accounting", "General Ledger"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Tüm muhasebe hesaplarının borç-alacak hareketleri ve detaylı defter ekstreleri.",
    keywords: ["general ledger", "defteri kebir", "muhasebe ekstresi", "borç alacak", "hesap ekstresi"],
  },
  {
    id: "acc_customer_ledger",
    title: "Customer Ledger",
    titleTr: "Müşteri Cari Hesap Ekstresi",
    url: e("accounting", "Customer Ledger"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Müşteri cari hesap bakiyeleri, faturalar ve tahsilat hareketleri.",
    keywords: ["müşteri ekstresi", "customer ledger", "cari bakiye", "alacak takibi"],
  },
  {
    id: "acc_supplier_ledger",
    title: "Supplier Ledger",
    titleTr: "Tedarikçi Cari Hesap Ekstresi",
    url: e("accounting", "Supplier Ledger"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Tedarikçi borç bakiyeleri, satıcı faturaları ve ödeme hareketleri.",
    keywords: ["tedarikçi ekstresi", "supplier ledger", "borç takibi", "satıcı ekstresi"],
  },
  {
    id: "acc_balance_sheet",
    title: "Balance Sheet",
    titleTr: "Bilanço Tablosu",
    url: e("accounting", "Balance Sheet"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Şirketin varlık, kaynak, aktif ve pasif durumunu gösteren finansal bilanço.",
    keywords: ["bilanço", "balance sheet", "aktif pasif", "varlıklar", "özkaynaklar"],
  },
  {
    id: "acc_profit_loss",
    title: "Profit and Loss",
    titleTr: "Kâr ve Zarar Tablosu (Gelir Tablosu)",
    url: e("accounting", "Profit and Loss"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Dönemsel satış gelirleri, maliyetler, faaliyet giderleri ve net kâr/zarar analizi.",
    keywords: ["kâr zarar", "profit loss", "gelir tablosu", "net kâr", "gelir gider"],
  },
  {
    id: "acc_trial_balance",
    title: "Trial Balance",
    titleTr: "Mizan Raporu",
    url: e("accounting", "Trial Balance"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Hesap planı bazında borç-alacak toplamları ve devir mizanalari.",
    keywords: ["mizan", "trial balance", "aylık mizan", "genel mizan"],
  },
  {
    id: "acc_cash_flow",
    title: "Cash Flow",
    titleTr: "Nakit Akım Raporu",
    url: e("accounting", "Cash Flow"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Kasa, banka ve nakit giriş-çıkış akışlarının takibi.",
    keywords: ["nakit akım", "cash flow", "kasa banka", "finansal akış"],
  },
  {
    id: "acc_financial_reports",
    title: "Financial Reports",
    titleTr: "Finansal Raporlar",
    url: e("accounting", "Financial Reports"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Bilanço, kâr-zarar, nakit akım ve mizan raporlarının toplu modülü.",
    keywords: ["finansal rapor", "financial reports", "bilanço", "gelir tablosu", "mizan"],
  },
  {
    id: "acc_consolidated_report",
    title: "Consolidated Report",
    titleTr: "Konsolide Rapor",
    url: "/accounting",
    category: "Raporlar",
    workspace: "accounting",
    description: "Tüm grup ve şirket birleşik (konsolide) raporları.",
    keywords: ["konsolide", "birleşik rapor", "group", "konsolide bilanço"],
  },
  {
    id: "acc_ledgers",
    title: "Ledgers",
    titleTr: "Defterler",
    url: e("accounting", "Ledgers"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Genel, müşteri ve tedarikçi defterlerinin (ekstrelerin) toplu modülü.",
    keywords: ["defter", "ledger", "ekstre", "muhasebe ekstresi", "defterler"],
  },
  {
    id: "acc_profitability",
    title: "Profitability",
    titleTr: "Kârlılık",
    url: e("accounting", "Profitability"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Kârlılık ve marj analizleri modülü.",
    keywords: ["kârlılık", "kar marjı", "profitability", "marj analizi"],
  },
  {
    id: "acc_other_reports",
    title: "Other Reports",
    titleTr: "Diğer Raporlar",
    url: e("accounting", "Other Reports"),
    category: "Raporlar",
    workspace: "accounting",
    description: "Diğer muhasebe raporları modülü.",
    keywords: ["diğer raporlar", "other reports", "muhtelif rapor"],
  },
];

export const MANUFACTURING_WORKSPACE_MENU_ITEMS: WorkspaceMenuItem[] = [
  {
    id: "mfg_bom",
    title: "BOM (Bill of Materials)",
    titleTr: "Ürün Reçetesi / Malzeme Listesi",
    url: e("manufacturing", "BOM"),
    category: "Katalog",
    workspace: "manufacturing",
    description: "Mamul ve yarı mamullerin hammadde bileşenleri ve operasyon reçeteleri.",
    keywords: ["bom", "ürün reçetesi", "malzeme listesi", "üretim reçetesi"],
  },
  {
    id: "mfg_work_order",
    title: "Work Order",
    titleTr: "Üretim İş Emri",
    url: e("manufacturing", "Work Order"),
    category: "İşlemler",
    workspace: "manufacturing",
    description: "Üretim hattına verilen imalat emri ve miktar takibi.",
    keywords: ["iş emri", "work order", "üretim emri", "imalat"],
  },
  {
    id: "mfg_job_card",
    title: "Job Card",
    titleTr: "İş Kartı / Operasyon Kaydı",
    url: e("manufacturing", "Job Card"),
    category: "İşlemler",
    workspace: "manufacturing",
    description: "İstasyon bazında operatör başlama-bitiş ve süre takipleri.",
    keywords: ["iş kartı", "job card", "operasyon", "istasyon"],
  },
  {
    id: "mfg_production_plan",
    title: "Production Plan",
    titleTr: "Üretim Planlama",
    url: e("manufacturing", "Production Plan"),
    category: "Araçlar",
    workspace: "manufacturing",
    description: "Sipariş ve tahminlere dayalı ana üretim planlaması.",
    keywords: ["üretim planı", "production plan", "kapasite planlama"],
  },
  {
    id: "mfg_warehouse",
    title: "Warehouse",
    titleTr: "Depo",
    url: e("manufacturing", "Warehouse"),
    category: "İşlemler",
    workspace: "manufacturing",
    description: "Depo hareketleri, transfer ve stok sayım işlemleri.",
    keywords: ["depo", "warehouse", "depo transferi", "stok sayım"],
  },
  {
    id: "mfg_stock_entry",
    title: "Stock Entry",
    titleTr: "Stok Girişi",
    url: e("manufacturing", "Stock Entry"),
    category: "İşlemler",
    workspace: "manufacturing",
    description: "Üretim, transfer ve düzeltme için stok giriş-çıkış kayıtları.",
    keywords: ["stok girişi", "stock entry", "stok hareketi", "transfer kaydı"],
  },
  {
    id: "mfg_forecasting",
    title: "Forecasting",
    titleTr: "Talep Tahmini",
    url: e("manufacturing", "Forecasting"),
    category: "İşlemler",
    workspace: "manufacturing",
    description: "Talep tahminleme ve planlama verileri.",
    keywords: ["talep tahmini", "forecasting", "tahminleme", "demand"],
  },
  {
    id: "mfg_master_production_schedule",
    title: "Master Production Schedule",
    titleTr: "Ana Üretim Programı",
    url: "/landed-cost-voucher",
    category: "İşlemler",
    workspace: "manufacturing",
    description: "Ana üretim programı (MPS) planı.",
    keywords: ["ana üretim programı", "master production schedule", "mps", "üretim programı"],
  },
  {
    id: "mfg_sales_forecast",
    title: "Sales Forecast",
    titleTr: "Satış Tahmini",
    url: e("manufacturing", "Sales Forecast"),
    category: "İşlemler",
    workspace: "manufacturing",
    description: "Satış tahminleri ve plan senaryoları.",
    keywords: ["satış tahmini", "sales forecast", "satış planı", "tahmin"],
  },
  {
    id: "mfg_production_planning_report",
    title: "Production Planning Report",
    titleTr: "Planlama Raporu",
    url: e("manufacturing", "Production Planning Report"),
    category: "Raporlar",
    workspace: "manufacturing",
    description: "Üretim planlama ve kapasite raporları.",
    keywords: ["planlama raporu", "production planning", "üretim planı", "kapasite"],
  },
  {
    id: "mfg_tools",
    title: "Tools",
    titleTr: "Araçlar",
    url: e("manufacturing", "Tools"),
    category: "Araçlar",
    workspace: "manufacturing",
    description: "Üretim yardımcı araçları modülü.",
    keywords: ["araçlar", "tools", "üretim araçları", "yardımcı araç"],
  },
  {
    id: "mfg_reports_group",
    title: "Reports",
    titleTr: "Raporlar",
    url: e("manufacturing", "Reports"),
    category: "Raporlar",
    workspace: "manufacturing",
    description: "Üretim raporları toplu modülü.",
    keywords: ["üretim raporları", "manufacturing reports", "iş emri özeti", "duruş analizi"],
  },
  {
    id: "mfg_reports_production_planning",
    title: "Production Planning Report",
    titleTr: "Planlama Raporu",
    url: e("manufacturing", "Reports Production Planning"),
    category: "Raporlar",
    workspace: "manufacturing",
    description: "Raporlar altında üretim planlama raporu.",
    keywords: ["planlama raporu", "reports production planning", "üretim plan raporu"],
  },
  {
    id: "mfg_work_order_summary",
    title: "Work Order Summary",
    titleTr: "İş Emri Özeti",
    url: e("manufacturing", "Work Order Summary"),
    category: "Raporlar",
    workspace: "manufacturing",
    description: "İş emirleri özet ve durum raporu.",
    keywords: ["iş emri özeti", "work order summary", "iş emri", "üretim emri"],
  },
  {
    id: "mfg_quality_inspection_summary",
    title: "Quality Inspection Summary",
    titleTr: "Kalite Kontrol Özeti",
    url: e("manufacturing", "Quality Inspection Summary"),
    category: "Raporlar",
    workspace: "manufacturing",
    description: "Kalite kontrol sonuçları özet raporu.",
    keywords: ["kalite kontrol", "quality inspection", "kalite raporu", "kontrol"],
  },
  {
    id: "mfg_downtime_analysis",
    title: "Downtime Analysis",
    titleTr: "Duruş Analizi",
    url: e("manufacturing", "Downtime Analysis"),
    category: "Raporlar",
    workspace: "manufacturing",
    description: "Makine ve hat duruş analizi.",
    keywords: ["duruş analizi", "downtime analysis", "makine duruşu", "hat duruşu"],
  },
  {
    id: "mfg_job_card_summary",
    title: "Job Card Summary",
    titleTr: "İş Kartı Özeti",
    url: e("manufacturing", "Job Card Summary"),
    category: "Raporlar",
    workspace: "manufacturing",
    description: "İş kartı özet ve ilerleme raporu.",
    keywords: ["iş kartı özeti", "job card summary", "iş kartı", "üretim kartı"],
  },
];

export const SUBCONTRACTING_WORKSPACE_MENU_ITEMS: WorkspaceMenuItem[] = [
  {
    id: "sub_inward_order",
    title: "Subcontracting Order",
    titleTr: "Fason Üretim Siparişi",
    url: e("subcontracting", "Inward Subcontracting Order"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "Fason tedarikçiye verilen hammadde gönderimli üretim emri.",
    keywords: ["fason", "subcontracting", "fason sipariş", "fason emri"],
  },
  {
    id: "sub_delivery",
    title: "Subcontracting Delivery",
    titleTr: "Fason Malzeme Çıkış İrsaliyesi",
    url: e("subcontracting", "Subcontracting Delivery"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "Fason üreticiye gönderilen hammaddelerin sevk irsaliyesi.",
    keywords: ["fason teslimat", "fason sevk", "malzeme çıkışı"],
  },
  {
    id: "sub_receipt",
    title: "Subcontracting Receipt",
    titleTr: "Fason Mal Kabul İrsaliyesi",
    url: e("subcontracting", "Subcontracting Receipt"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "Fasoncudan tamamlanıp gelen ürünlerin depoya kabul irsaliyesi.",
    keywords: ["fason mal kabul", "fason giriş", "fason irsaliyesi"],
  },
  {
    id: "sc_inward_subcontracting",
    title: "Inward Subcontracting",
    titleTr: "İşletme Dışı Giriş",
    url: e("subcontracting", "Inward Subcontracting"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "İşletme dışı (fason) giriş işlemleri modülü.",
    keywords: ["fason giriş", "inward", "işletme dışı", "fason"],
  },
  {
    id: "sc_outward_subcontracting",
    title: "Outward Subcontracting",
    titleTr: "İşletme Dışı Çıkış",
    url: e("subcontracting", "Outward Subcontracting"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "İşletme dışı (fason) çıkış işlemleri modülü.",
    keywords: ["fason çıkış", "outward", "hammadde sevk", "işletme dışı"],
  },
  {
    id: "sc_purchase_order",
    title: "Purchase Order",
    titleTr: "Satınalma Emri",
    url: e("subcontracting", "Purchase Order"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "Fason tedarik satınalma emirleri.",
    keywords: ["satınalma emri", "purchase order", "fason satınalma", "tedarik emri"],
  },
  {
    id: "sc_raw_materials",
    title: "Subcontracting Raw Materials",
    titleTr: "İşletme Dışı Hammadde",
    url: e("subcontracting", "Subcontracting Raw Materials"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "Fason üretim hammadde yönetimi.",
    keywords: ["hammadde", "raw material", "fason hammadde", "hammadde sevk"],
  },
  {
    id: "sc_ops_quality",
    title: "Operations & Quality",
    titleTr: "Operasyonlar & Kalite",
    url: e("subcontracting", "Operations"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "Fason operasyon ve kalite kontrol modülü.",
    keywords: ["operasyon", "fason operasyon", "fason kalite", "kalite kontrol"],
  },
  {
    id: "sc_inspection",
    title: "Inspection",
    titleTr: "Kontrol",
    url: e("subcontracting", "Inspection"),
    category: "İşlemler",
    workspace: "subcontracting",
    description: "Fason teslimat kalite kontrolü.",
    keywords: ["kontrol", "inspection", "fason kontrol", "kalite kontrol"],
  },
  {
    id: "sc_job_work_register",
    title: "Job Work Register",
    titleTr: "İş Kayıt Defteri",
    url: e("subcontracting", "Job Work Register"),
    category: "Raporlar",
    workspace: "subcontracting",
    description: "İşletme dışı iş kayıtları defteri.",
    keywords: ["iş kayıt defteri", "job work register", "fason kayıtları"],
  },
  {
    id: "sc_tools",
    title: "Tools",
    titleTr: "Araçlar",
    url: e("subcontracting", "Tools"),
    category: "Araçlar",
    workspace: "subcontracting",
    description: "Fason yardımcı araçları modülü.",
    keywords: ["fason araçları", "tools", "yardımcı araç"],
  },
  {
    id: "sc_reports_group",
    title: "Reports",
    titleTr: "Raporlar",
    url: e("subcontracting", "Reports"),
    category: "Raporlar",
    workspace: "subcontracting",
    description: "Fason raporları toplu modülü.",
    keywords: ["fason raporları", "subcontracting reports", "fason özet"],
  },
  {
    id: "sc_order_summary",
    title: "Subcontracting Order Summary",
    titleTr: "İşletme Dışı Emri Özeti",
    url: e("subcontracting", "Subcontracting Order Summary"),
    category: "Raporlar",
    workspace: "subcontracting",
    description: "Fason emir özet raporu.",
    keywords: ["fason emri özeti", "subcontracting order", "fason emri"],
  },
  {
    id: "sc_settings",
    title: "Settings",
    titleTr: "Ayarlar",
    url: e("subcontracting", "Settings"),
    category: "Ayarlar",
    workspace: "subcontracting",
    description: "Fason modülü parametre ayarları.",
    keywords: ["fason ayarları", "subcontracting settings", "parametre"],
  },
];

export const SELLING_WORKSPACE_MENU_ITEMS: WorkspaceMenuItem[] = [
  {
    id: "sell_sales_order",
    title: "Sales Order",
    titleTr: "Sipariş",
    url: e("selling", "Sales Order"),
    category: "İşlemler",
    workspace: "selling",
    description: "Satış siparişlerinin oluşturulması ve takibi.",
    keywords: ["sipariş", "sales order", "satış siparişi", "so"],
  },
  {
    id: "sell_quotations",
    title: "Quotations",
    titleTr: "Teklifler",
    url: e("selling", "Quotations"),
    category: "İşlemler",
    workspace: "selling",
    description: "Satış tekliflerinin hazırlanması.",
    keywords: ["teklif", "quotation", "satış teklifi", "fiş"],
  },
  {
    id: "sell_customers",
    title: "Customers",
    titleTr: "Müşteriler",
    url: e("selling", "Customers"),
    category: "Katalog",
    workspace: "selling",
    description: "Müşteri kartları ve hesap listesi.",
    keywords: ["müşteri", "customers", "müşteri kartı", "müşteri listesi"],
  },
  {
    id: "sell_sales_invoice",
    title: "Sales Invoice",
    titleTr: "Fatura",
    url: e("selling", "Sales Invoice"),
    category: "İşlemler",
    workspace: "selling",
    description: "Satış faturaları.",
    keywords: ["fatura", "sales invoice", "satış faturası", "tahakkuk"],
  },
  {
    id: "sell_delivery_note",
    title: "Delivery Note",
    titleTr: "Teslimat Notu",
    url: e("selling", "Delivery Note"),
    category: "İşlemler",
    workspace: "selling",
    description: "Teslimat ve sevkiyat kayıtları.",
    keywords: ["teslimat notu", "delivery note", "sevkiyat", "satış irsaliyesi"],
  },
  {
    id: "sell_reports_group",
    title: "Reports",
    titleTr: "Raporlar",
    url: e("selling", "Reports"),
    category: "Raporlar",
    workspace: "selling",
    description: "Satış raporları toplu modülü.",
    keywords: ["satış raporları", "sales reports", "satış analizi"],
  },
  {
    id: "sell_sales_analytics",
    title: "Sales Analytics",
    titleTr: "Satış Analizleri",
    url: e("selling", "Sales Analytics"),
    category: "Raporlar",
    workspace: "selling",
    description: "Satış performans analizi.",
    keywords: ["satış analizi", "sales analytics", "gelir analizi", "satış performansı"],
  },
  {
    id: "sell_sales_funnel",
    title: "Sales Funnel",
    titleTr: "Satış Hunisi",
    url: e("selling", "Sales Funnel"),
    category: "Raporlar",
    workspace: "selling",
    description: "Satış hunisi ve fırsat takibi.",
    keywords: ["satış hunisi", "sales funnel", "fırsat takibi", "pipeline"],
  },
  {
    id: "sell_customer_ledger_summary",
    title: "Customer Ledger Summary",
    titleTr: "Müşteri Defteri Özeti",
    url: e("selling", "Customer Ledger Summary"),
    category: "Raporlar",
    workspace: "selling",
    description: "Müşteri defteri (cari) özet raporu.",
    keywords: ["müşteri defteri", "customer ledger", "cari özet", "cari ekstresi"],
  },
  {
    id: "sell_settings",
    title: "Settings",
    titleTr: "Ayarlar",
    url: e("selling", "Settings"),
    category: "Ayarlar",
    workspace: "selling",
    description: "Satış modülü parametre ayarları.",
    keywords: ["satış ayarları", "selling settings", "parametre"],
  },
];

export const ALL_WORKSPACE_MENU_ITEMS: WorkspaceMenuItem[] = [
  ...STOCK_WORKSPACE_MENU_ITEMS,
  ...ACCOUNTING_WORKSPACE_MENU_ITEMS,
  ...MANUFACTURING_WORKSPACE_MENU_ITEMS,
  ...SUBCONTRACTING_WORKSPACE_MENU_ITEMS,
  ...SELLING_WORKSPACE_MENU_ITEMS,
];
