#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$DIR/main.py" ]; then
    SCRIPT="$DIR/main.py"
elif [ -f "$DIR/../../binaries/main.py" ]; then
    SCRIPT="$DIR/../../binaries/main.py"
elif [ -f "$DIR/../Resources/binaries/main.py" ]; then
    SCRIPT="$DIR/../Resources/binaries/main.py"
elif [ -f "$DIR/../binaries/main.py" ]; then
    SCRIPT="$DIR/../binaries/main.py"
else
    SCRIPT="$(pwd)/src-tauri/binaries/main.py"
fi

exec python3 -u "$SCRIPT" "$@"
