<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Arrow.Jobs.AspNetCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Builder" />
    <Using Include="Microsoft.AspNetCore.Http" />
    <Using Include="Microsoft.AspNetCore.Mvc" />
    <Using Include="Microsoft.AspNetCore.Routing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arrow.Http.AspNetCore\Arrow.Http.AspNetCore.csproj" />
    <ProjectReference Include="..\Arrow.Jobs.Abstractions\Arrow.Jobs.Abstractions.csproj" />
  </ItemGroup>

</Project>
